export const icons = {
    "Airplay": IconUilAirplay,
    "Airpods": IconUuiAirpods,
    "Alarm": IconTablerAlarm,
    "Alert": IconTablerAlertTriangle,
    "Announcement": IconMingcuteAnnouncementLine,
    "Aperture": IconTablerAperture,
    "Application": IconTablerAppWindow,
    "Archive": IconTablerArchive,
    "Art": IconUuiStand,
    "Astronomy": IconUuiTelescope,
    "Atom": IconTablerAtom,
    "Attachment": IconUuiPaperclip,
    "Automotive battery": IconTablerBatteryAutomotive,
    "Award": IconMajesticonsAwardLine,
    "Baby": IconLucideBaby,
    "Backpack": IconTablerBackpack,
    "Bad": IconUilThumbsDown,
    "Bank": IconMingcuteBankLine,
    "Banknote": IconTablerCashBanknote,
    "Battery": IconTablerBattery,
    "Bell": IconUuiBell03,
    "Bible": IconTablerBible,
    "Biology": IconTablerMicroscope,
    "Bitcoin": IconUuiCurrencyBitcoin,
    "Bluetooth": IconTablerBluetooth,
    "Bolt": IconTablerBolt,
    "Book": IconTablerBook2,
    "Books": IconTablerBooks,
    "Briefcase": IconUuiBriefcase01,
    "Browser": IconTablerBrowser,
    "Calculator": IconMajesticonsCalculatorLine,
    "Camera": IconTablerCamera,
    "Canvas": IconUuiStand,
    "Cash": IconTablerCash,
    "Certificate": IconMingcuteCertificate2Line,
    "Chalkboard": IconTablerChalkboard,
    "Championship": IconUuiAward01,
    "Charging": IconTablerBatteryCharging2,
    "Charity": IconUuiHeartHand,
    "Chart": IconUuiBarChart10,
    "Chemistry": IconTablerFlask,
    "Child": IconTablerMoodBoy,
    "Chrome cast": IconUuiChromeCast,
    "Circle": IconTablerCircle,
    "Clapperboard": IconLucideClapperboard,
    "Clock": IconTablerClock,
    "Cloud": IconTablerCloud,
    "Code": IconTablerCode,
    "Coins": IconUuiCoinsStacked02,
    "Cold": IconUuiThermometerCold,
    "Color": IconEvaColorPaletteOutline,
    "Color filter": IconTablerColorFilter,
    "Color picker": IconUuiDropper,
    "Color swatch": IconTablerColorSwatch,
    "Comet": IconMajesticonsCometLine,
    "Comment": IconUuiAnnotationDots,
    "Compass": IconUuiCompass03,
    "Compass (geometry)": IconUuiCompass,
    "Competition": IconUuiTrophy01,
    "Compressed file": IconTablerFileZip,
    "Container": IconUuiCube01,
    "Country": IconTablerFlag,
    "Credit card": IconUilCreditCard,
    "Crying": IconTablerMoodCry,
    "Cryptocurrency": IconUuiCryptocurrency01,
    "CPU": IconUuiCpuChip01,
    "Cube": IconUuiCube01,
    "Currency": IconTablerCurrency,
    "Currency exchange": IconUuiCoinsSwap01,
    "Data": IconUuiData,
    "Database": IconTablerDatabase,
    "Defense": IconUuiShield01,
    "Definition": IconIconParkOutlineParagraphAlphabet,
    "Design": IconIconParkOutlineGraphicDesign,
    "Destination": IconUuiGlobe05,
    "Development": IconTablerCode,
    "Diamond": IconTablerDiamond,
    "Dices": IconLucideDices,
    "Dictionary": IconTablerSortAZ,
    "Directions": IconTablerDirections,
    "Disc": IconUuiDisc01,
    "Document": IconTablerFile,
    "Dollar": IconUuiCurrencyDollar,
    "Droplet": IconTablerDroplet,
    "Dropper": IconUuiDropper,
    "Earn": IconUuiCoinsHand,
    "Earth": IconMajesticonsGlobeEarthLine,
    "Eclipse": IconUilMoonEclipse,
    "Eco battery": IconTablerBatteryEco,
    "Electricity": IconTablerBolt,
    "Emoji": IconTablerMoodSmile,
    "Envelope": IconTablerMail,
    "Eraser": IconUuiEraser,
    "Ethereum": IconUuiCurrencyEthereum,
    "Euro": IconUuiCurrencyEuro,
    "Face": IconTablerMoodSmile,
    "Face ID": IconUuiFaceId,
    "Female": IconTablerVenus,
    "File": IconTablerFile,
    "Finance": IconUuiLineChartUp01,
    "Fingerprint": IconUuiFingerprint04,
    "Fire": IconUilFire,
    "Flag": IconTablerFlag,
    "Flame": IconUilFire,
    "Flash": IconTablerBolt,
    "Flask": IconTablerFlask,
    "Folder": IconTablerFolder,
    "Fog": IconTablerCloudFog,
    "Fountain pen": IconUuiPenTool02,
    "Free": IconTablerFreeRights,
    "Fun": IconTablerMoodHappy,
    "Gambling": IconLucideDices,
    "Gamepad": IconLucideGamepad2,
    "Gem": IconTablerDiamond,
    "Geography": IconUuiGlobe02,
    "Geometry": IconUuiCompass,
    "Gift": IconUuiGift01,
    "Git": IconTablerGitMerge,
    "Glasses": IconUuiGlasses02,
    "Globe": IconUuiGlobe02,
    "Good": IconUilThumbsUp,
    "Graduation": IconTablerSchool,
    "Happiness": IconTablerMoodSmile,
    "Hard drive": IconUuiHardDrive,
    "Haze": IconTablerHaze,
    "Headphones": IconTablerHeadphones,
    "Heat": IconUilFire,
    "Help": IconMingcuteQuestionLine,
    "Hexagon": IconTablerHexagon,
    "Hexagons": IconTablerHexagons,
    "History": IconTablerHistory,
    "Holidays": IconMingcuteTree4Line,
    "Image": IconTablerPhoto,
    "Images": IconMingcutePhotoAlbumLine,
    "Inbox": IconUuiInbox01,
    "Input": IconUuiTextInput,
    "Islam": IconUuiMoonStar,
    "Jewish": IconIconParkOutlineTwoTriangles,
    "Justice": IconTablerScale,
    "Key": IconMingcuteKey1Line,
    "Keyboard": IconTablerKeyboard,
    "Language": IconTablerLanguage,
    "Laptop": IconUuiLaptop01,
    "Layout": IconTablerLayoutBoard,
    "Lecture": IconTablerChalkboard,
    "Lens": IconTablerAperture,
    "Lesson": IconTablerBook2,
    "Library": IconTablerBooks,
    "Lightbulb": IconMajesticonsLightbulbShineLine,
    "Lightning": IconTablerCloudStorm,
    "List": IconTablerList,
    "Location": IconTablerMapPin,
    "Lock": IconUuiLock03,
    "Magazine": IconTablerBook,
    "Magic": IconUuiMagicWand01,
    "Magic wand": IconUuiMagicWand01,
    "Mail": IconTablerMail,
    "Male": IconTablerMars,
    "Man": IconTablerMan,
    "Map": IconTablerMap,
    "Math": IconTablerMath,
    "Medal": IconUuiAward03,
    "Megaphone": IconMingcuteAnnouncementLine,
    "Message": IconTablerMessageDots,
    "Messages": IconTablerMessages,
    "Microscope": IconTablerMicroscope,
    "Mist": IconTablerMist,
    "Money": IconUuiCoinsStacked02,
    "Money bill": IconTablerCashBanknote,
    "Moon": IconTablerMoon,
    "Movie": IconTablerMovie,
    "Navigation": IconTablerNavigation,
    "Negative": IconUilThumbsDown,
    "Neutral": IconTablerMoodEmpty,
    "News": IconUilNewspaper,
    "Night": IconTablerMoonStars,
    "Notification": IconTablerNotification,
    "Octagon": IconTablerOctagon,
    "Optics": IconUuiGlasses02,
    "Painting": IconTablerBrush,
    "Palette": IconEvaColorPaletteOutline,
    "Palm tree": IconMingcuteTree4Line,
    "Paperclip": IconUuiPaperclip,
    "Paper plane": IconTablerSend,
    "Passport": IconUuiPassport,
    "Password": IconUuiPasscode,
    "Paid": IconTablerCoin,
    "Pay": IconMajesticonsMoneyHandLine,
    "Pen": IconMingcutePen2Line,
    "Pencil": IconTablerPencil,
    "Pentagon": IconTablerPentagon,
    "People": IconUilUsersAlt,
    "Phone": IconTablerPhone,
    "Photo": IconTablerPhoto,
    "Photo album": IconMingcutePhotoAlbumLine,
    "Photos": IconMingcutePhotoAlbumLine,
    "Physics": IconTablerAtom,
    "Picture": IconTablerPhoto,
    "Pictures": IconMingcutePhotoAlbumLine,
    "Piggy bank": IconTablerPigMoney,
    "Planet": IconTablerPlanet,
    "Positive": IconUilThumbsUp,
    "Power": IconTablerBolt,
    "Pound": IconUuiCurrencyPound,
    "Presentation": IconTablerPresentation,
    "Programming": IconTablerCode,
    "Prompt": IconTablerPrompt,
    "QR code": IconUuiQrCode01,
    "Question": IconMingcuteQuestionLine,
    "Rain": IconUuiCloudRaining05,
    "Rainbow": IconTablerRainbow,
    "Random": IconLucideDices,
    "Reading": IconUuiGlasses02,
    "Receipt": IconUilReceipt,
    "Rocket": IconUuiRocket01,
    "Route": IconTablerRoute,
    "Ruble": IconUuiCurrencyRuble,
    "Ruler": IconTablerRuler2,
    "Rupee": IconUuiCurrencyRupee,
    "Sadness": IconTablerMoodSad,
    "Safe": IconUuiSafe,
    "Salary": IconUuiCoinsHand,
    "Sale": IconMingcuteSaleLine,
    "Savings": IconTablerPigMoney,
    "Scale": IconTablerScale,
    "Scan": IconUuiScan,
    "School": IconTablerSchool,
    "Science": IconTablerAtom,
    "Sea": IconUuiWaves,
    "Security": IconUuiShield01,
    "Send": IconTablerSend,
    "Server": IconTablerServer,
    "Shield": IconUuiShield01,
    "Shooting star line": IconMajesticonsShootingStarLine,
    "Shopping": IconTablerShoppingCart,
    "Shopping bag": IconTablerShoppingBag,
    "Shopping cart": IconTablerShoppingCart,
    "Smartwatch": IconTablerDeviceWatch,
    "Smile": IconTablerMoodSmile,
    "Snooze": IconTablerAlarmSnooze,
    "Snow": IconUuiCloudSnowing02,
    "Snowflake": IconUilSnowflake,
    "Space": IconTablerPlanet,
    "Speakerphone": IconMingcuteAnnouncementLine,
    "Square": IconTablerSquare,
    "Star": IconTablerStar,
    "Stars": IconUuiStars03,
    "Statistics": IconUuiBarChart10,
    "Storm": IconTablerStorm,
    "Stopwatch": IconIconParkOutlineStopwatch,
    "Sun": IconTablerSun,
    "Sunrise": IconTablerSunset2,
    "Sunset": IconTablerSunset2,
    "Table": IconTablerTable,
    "Tag": IconTablerTag,
    "Telescope": IconUuiTelescope,
    "Temperature": IconTablerTemperature,
    "Terminal": IconTablerTerminal2,
    "Thumbs down": IconUilThumbsDown,
    "Thumbs up": IconUilThumbsUp,
    "Ticket": IconUuiTicket01,
    "Time": IconTablerClock,
    "Timer": IconIconParkOutlineStopwatch,
    "Tram": IconUuiTram,
    "Translation": IconTablerLanguage,
    "Trend": IconTablerTrendingUp,
    "Trending down": IconTablerTrendingDown,
    "Trending up": IconTablerTrendingUp,
    "Triangle": IconTablerTriangle,
    "Trophy": IconUuiTrophy01,
    "Tropical": IconMingcuteTree4Line,
    "University": IconTablerSchool,
    "Unlock": IconUuiLockUnlocked03,
    "UV": IconTablerUvIndex,
    "Vacation": IconMingcuteTree4Line,
    "Wait": IconUuiHourglass01,
    "Wallet": IconTablerWallet,
    "Warm": IconUuiThermometerWarm,
    "Warning": IconTablerAlertTriangle,
    "Watch (clock)": IconUuiWatchCircle,
    "Water": IconTablerDroplet,
    "Waves": IconUuiWaves,
    "Weather": IconUuiCloudSun01,
    "Whirl": IconTablerWhirl,
    "Wind": IconTablerWind,
    "Wink": IconTablerMoodWink,
    "Woman": IconTablerWoman,
    "Work": IconUuiBriefcase01,
    "Yen": IconUuiCurrencyYen
} as const
